name: CI
on:
    pull_request:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                node-version: 20
            - run: npm test